### ISSUE TITLE
(Not an issue) How do you run the XResources script?

### ISSUE THREAD

**Issue by buenahora** [nightsense/seabird#1]

**Comment by nightsense** [comment]
hey buenahora, I think there may be minor differences in how this works between unix-like operating systems, but this "standard method" will likely work:

- copy the contents of [Xresources](https://github.com/nightsense/seabird/blob/master/terminal/Xresources) into the file `~/.Xresources` on your system (create this file if necessary) and save
- run `xrdb -merge ~/.Xresources` to load the settings from this file
- open a new terminal window (xterm or urxvt) and the colour scheme should be active

Note that the seabird Xresources file has the petrel (dark) theme enabled, with the seagull (light) theme commented out. To switch to the light theme, comment out the blocks labelled "petrel" and uncomment the "seagull" blocks.

**Comment by buenahora** [comment]
thank you for the help!
