### ISSUE TITLE
support for alacritty terminal

### ISSUE THREAD

**Issue by pirey** [nightsense/seabird#11]
Hi, how can I setup this colorscheme in alacritty terminal? https://github.com/jwilm/alacritty

Thanks

**Comment by nightsense** [comment]
Hi @pirey, I wasn't aware of alacritty so thanks for bringing it to my attention, I just may switch over to it! I've added seabird configs [here](https://github.com/nightsense/seabird/blob/master/terminal/alacritty.md).

**Comment by pirey** [comment]
awesome!
gonna try it right away
