### ISSUE TITLE
NeoVim compatibility 

### ISSUE THREAD

**Issue by jesusgalvan** [nightsense/seabird#2]
Not an issue, but more a comment.
I was having an issue with NeoVim not displaying the correct colors:

**Incorrect:**
![image](https://cloud.githubusercontent.com/assets/2798097/24460172/c2404b58-149d-11e7-9b62-aaa0dff22de4.png)

The options `set termguicolors` fixed it for me.

**Correct:**
![image](https://cloud.githubusercontent.com/assets/2798097/24460199/df6d1d3c-149d-11e7-8816-24710653624f.png)

**Comment by jesusgalvan** [comment]
Great theme! Thanks :)

**Comment by nightsense** [comment]
Thanks for letting me know, I've edited the readme.
