### ISSUE TITLE
Add Mac OSX Terminal colors config file

### ISSUE THREAD

**Issue by denvaar** [nightsense/seabird#3]

**Comment by nightsense** [comment]
Thanks for the request, shiny new [configs](https://github.com/nightsense/seabird/tree/master/terminal/osx-terminal) added :sparkles:.

Let me know about any issues, I have no experience with Mac terminals.

**Comment by denvaar** [comment]
Very nice job with this, thanks. Did you use something to generate the terminal config, or did you figure out how on your own?

**Comment by nightsense** [comment]
@denvaar I just imported the 'Solarized Light' theme from [this repo](https://github.com/lysyi3m/osx-terminal-themes), adjusted the colours, and exported the new theme files
