### ISSUE TITLE
Terminal Configuration for Gnome Terminal

### ISSUE THREAD

**Issue by 0xelectron** [nightsense/seabird#6]
It would be great if you could provide Terminal Configuration file for Gnome Terminal.

P.S. It's Beautiful.

**Comment by nightsense** [comment]
@0xelectron thanks! :frog:

gnome terminal "install script" [ready to go](https://github.com/nightsense/gnome-terminal-colours-seabird)

If you run into any issues let me know.

**Comment by 0xelectron** [comment]
Wow! Thank you.
