### ISSUE TITLE
Vscode

### ISSUE THREAD

**Issue by bbrakenhoff** [nightsense/seabird#8]
Hi,

I just wanted to let you know I am working on a version of your seabird theme for visual studio code.
You can find it here: https://github.com/bbrakenhoff/seabird-vscode .

**Comment by bbrakenhoff** [comment]
I also started working on a version for Intellij, because I really like your theme, but I use 2 different IDE's. You can find the repo here: https://github.com/bbrakenhoff/seabird-intellij

**Comment by nightsense** [comment]
Thanks! :frog: I've linked to both in the readme now.
